export {default as HomePage} from './client/Home/homePage'
export {default as Product} from './client/Product/productList'

export {default as DashBoard} from './admin/Dashboard/dashboard'
export {default as EmployeeScreen} from './admin/Employee/employeeScreen'
export {default as AddEditEmployee} from './admin/Employee/addEditEmployee'
export {default as EditPermission} from './admin/Employee/editPermission'
export {default as BrandScreen} from './admin/Brand/brandScreen'
export {default as CategoryScreen} from './admin/Category/categoryScreen'
export {default as ProductScreen} from './admin/Product/productScreen'
export {default as AddEditProduct} from './admin/Product/addEditScreen'
export {default as ProductSampleScreen} from './admin/ProductSample/productSampleScreen'
export {default as AddEditProductSample} from './admin/ProductSample/addEditScreen'
export {default as ImportScreen} from './admin/Import/importScreen'
export {default as AddImport} from './admin/Import/addImport'
export {default as DetailImport} from './admin/Import/detailImport'
export {default as CustomerScreen} from './admin/Customer/customerScreen'
export {default as EditCustomer} from './admin/Customer/editCustomer'
export {default as VoucherScreen} from './admin/Voucher/voucherScreen'
export {default as AddEditVoucher} from './admin/Voucher/addEditVoucher'
export {default as AdminLogin} from './admin/Auth/login'
export {default as ForgotPasword} from './admin/Auth/forgotPassword'
export {default as ResetPassword} from './admin/Auth/resetPassword'
// export {default as ProfileScreen} from './admin/Profile/profileScreen'
export {default as ChangePasswordScreen} from './admin/Profile/changePasswordScreen'


export {default as NotFound} from './Error/notFound'